<script setup>
import { MoreHorizontal, Search, UserPlus } from 'lucide-vue-next'
import UiBadge from '../UiBadge.vue'
import UiButton from '../UiButton.vue'
defineProps({ students: { type: Array, required: true } })
defineEmits(['select', 'add'])
</script>
<template>
  <div class="section-card overflow-hidden">
    <div class="flex flex-col gap-3 border-b p-4 sm:flex-row sm:items-center sm:justify-between sm:p-5"><div><p class="font-display text-lg font-extrabold">Estudiantes de la sección</p><p class="muted mt-1 text-sm">{{ students.length }} registros visibles</p></div><div class="flex gap-2"><div class="relative flex-1 sm:w-56"><Search class="muted absolute left-3 top-1/2 size-4 -translate-y-1/2" /><input class="control h-10 pl-9" placeholder="Buscar estudiante" /></div><UiButton size="sm" icon-only class="sm:hidden" @click="$emit('add')"><UserPlus class="size-4" /></UiButton><UiButton size="sm" class="hidden sm:inline-flex" @click="$emit('add')"><template #icon><UserPlus class="size-4" /></template>Inscribir</UiButton></div></div>
    <div class="hidden overflow-x-auto md:block"><table class="w-full min-w-[760px] text-left"><thead class="bg-[rgb(var(--surface-muted))] text-xs uppercase tracking-wider text-[rgb(var(--muted))]"><tr><th class="px-5 py-3">Estudiante</th><th class="px-5 py-3">Cédula escolar</th><th class="px-5 py-3">Asistencia</th><th class="px-5 py-3">Promedio</th><th class="px-5 py-3">Estado</th><th class="px-5 py-3"></th></tr></thead><tbody class="divide-y"><tr v-for="student in students" :key="student.id" class="cursor-pointer transition hover:bg-brand-50/40 dark:hover:bg-brand-950/20" @click="$emit('select', student)"><td class="px-5 py-4"><div class="flex items-center gap-3"><span class="grid size-9 place-items-center rounded-xl bg-brand-950 text-xs font-bold text-white">{{ student.initials }}</span><div><p class="text-sm font-bold">{{ student.name }}</p><p class="muted text-xs">5.º “A”</p></div></div></td><td class="muted px-5 py-4 text-sm">{{ student.id }}</td><td class="px-5 py-4 text-sm font-semibold">{{ student.attendance }}%</td><td class="px-5 py-4 text-sm font-bold">{{ student.average }}</td><td class="px-5 py-4"><UiBadge :tone="student.status === 'Al día' ? 'success' : 'warning'" dot>{{ student.status }}</UiBadge></td><td class="px-5 py-4"><button class="muted rounded-lg p-2 hover:bg-[rgb(var(--surface))]"><MoreHorizontal class="size-4" /></button></td></tr></tbody></table></div>
    <div class="divide-y md:hidden"><button v-for="student in students" :key="student.id" class="flex w-full items-center gap-3 p-4 text-left transition active:bg-brand-50 dark:active:bg-brand-950/30" @click="$emit('select', student)"><span class="grid size-11 shrink-0 place-items-center rounded-2xl bg-brand-950 text-xs font-bold text-white">{{ student.initials }}</span><span class="min-w-0 flex-1"><strong class="block truncate text-sm">{{ student.name }}</strong><span class="muted mt-1 block text-xs">{{ student.id }} · Asistencia {{ student.attendance }}%</span></span><span class="text-right"><UiBadge :tone="student.status === 'Al día' ? 'success' : 'warning'">{{ student.status }}</UiBadge><strong class="mt-1.5 block text-sm">{{ student.average }}</strong></span></button></div>
  </div>
</template>
